# Generated by Django 4.2.5 on 2023-09-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_test', '0003_rename_question_question_question_text_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_user_question_answer'),
        ),
    ]
