# Generated by Django 4.2.5 on 2023-09-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_test', '0004_answer_unique_user_question_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
