# Generated by Django 4.2.5 on 2023-09-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_test', '0006_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='unique_user_question_answer',
        ),
    ]
